package in.tamchow.fractal.color;
/**
 * A few constant values for coloring modes
 */
public final class Colors {
    public static final class CALCULATIONS {
        public static final int COLOR_DIVIDE_NORMALIZED = 0, COLOR_MULTIPLY_NORMALIZED = 1, COLOR_GRAYSCALE_HIGH_CONTRAST = 2, COLOR_GRAYSCALE_LOW_CONTRAST = 3, COLOR_NEWTON_STRIPES = 4, COLOR_NEWTON_NORMALIZED = 5, TRIANGLE_AREA_INEQUALITY_SPLINE = 6, CURVATURE_AVERAGE_SPLINE = 7, STRIPE_AVERAGE_SPLINE = 8, DISTANCE_ESTIMATION_GRAYSCALE = 9, SIMPLE = 10, SIMPLE_SMOOTH = 11, TRIANGLE_AREA_INEQUALITY_LINEAR = 12, CURVATURE_AVERAGE_LINEAR = 13, STRIPE_AVERAGE_LINEAR = 14, COLOR_DIVIDE_DIRECT = 15, COLOR_MULTIPLY_DIRECT = 16, COLOR_HISTOGRAM = 17, COLOR_HISTOGRAM_LINEAR = 18, COLOR_NEWTON_CLASSIC = 19, SIMPLE_DISTANCE_ESTIMATION = 20, DISTANCE_ESTIMATION_COLOR = 21;
    }
    public static final class PALETTE {
        public static final int RANDOM = 0, CUSTOM = 1;
    }
    public static final class RGBCOMPONENTS {
        public static final int RED = 0, GREEN = 1, BLUE = 2;
    }
}
