package in.tamchow.fractal.color;
/**
 * A few constant values for coloring modes
 */
public final class Colors {
    public static final class CALCULATIONS {
        public static final int COLOR_DIVIDE_NORMALIZED = 0, COLOR_MULTIPLY_NORMALIZED = 1, COLOR_GRAYSCALE_HIGH_CONTRAST = 2, COLOR_GRAYSCALE_LOW_CONTRAST = 3, COLOR_NEWTON_STRIPES = 4, COLOR_NEWTON_NORMALIZED = 5, TRIANGLE_AREA_INEQUALITY_SPLINE = 6, CURVATURE_AVERAGE_SPLINE = 7, STRIPE_AVERAGE_SPLINE = 8, DISTANCE_ESTIMATION_GRAYSCALE = 9, SIMPLE = 10, SIMPLE_SMOOTH = 11, TRIANGLE_AREA_INEQUALITY_LINEAR = 12, CURVATURE_AVERAGE_LINEAR = 13, STRIPE_AVERAGE_LINEAR = 14, COLOR_DIVIDE_DIRECT = 15, COLOR_MULTIPLY_DIRECT = 16, COLOR_HISTOGRAM = 17, COLOR_HISTOGRAM_LINEAR = 18, COLOR_NEWTON_CLASSIC = 19, SIMPLE_DISTANCE_ESTIMATION = 20, DISTANCE_ESTIMATION_COLOR = 21, ORBIT_TRAP_MIN = 22, ORBIT_TRAP_MAX = 23, ORBIT_TRAP_AVG = 24, LINE_TRAP_MIN = 25, LINE_TRAP_MAX = 26, LINE_TRAP_AVG = 27, GAUSSIAN_INT_DISTANCE_LINEAR = 28, EPSILON_CROSS_SPLINE = 29, EPSILON_CROSS_LINEAR = 30, GAUSSIAN_INT_DISTANCE_SPLINE = 31, DOMAIN_COLORING = 32;
    }
    public static final class PALETTE {
        public static final int RANDOM_PALETTE = 0, CUSTOM_PALETTE = 1, GRADIENT_PALETTE = 2, SMOOTH_PALETTE_LINEAR = 3, SMOOTH_PALETTE_SPLINE = 4, SHADE_PALETTE = 5;
    }
    public static final class RGBCOMPONENTS {
        public static final int ALPHA = 3, RED = 2, GREEN = 1, BLUE = 0;
    }
}
